<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>latest</LangVersion>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>MemoryCleaner</AssemblyName>
    <RootNamespace>MemoryCleaner</RootNamespace>
    <Version>0.2.0</Version>
    <Optimize>true</Optimize>
    <DebugSymbols>false</DebugSymbols>
    <DebugType>none</DebugType>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>
</Project>
